


let t = document.body.firstElementChild                 //  selected the table using DOM.....

console.log(t)


//  following are some table navigation methods of DOM....


console.log(t.rows)                     //  gives the collection of all the table rows.....
console.log(t.caption)                  //  gives the caption of the table.....
console.log(t.tHead)                    //  gives the thead 'tag' of the table.....
console.log(t.tFoot)                    //  gives the tfoot 'tag' of the table.....
console.log(t.tBodies)                  //  gives the collection of all the tbody 'tags'.....

console.log('\n')


console.log(t.tBodies[0].rows)                  //  gives the collection of all the rows in the first tbody 'tag'.....

console.log(t.rows[2].cells)                    //  gives the td and th 'tags' of the selected table row.......

console.log(t.rows[2].rowIndex)                 //  gives the row index of the selected table row.......

console.log(t.rows[4].cells[0].cellIndex)       //  gives the cell index of the selected table data.......

t.rows[3].cells[1].style.backgroundColor = "red"        //  selected a cell and changed its background color to red......



